
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - 'develop'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftps://<server-ip>:10001'
    username: '<ftp-username>'
    password: '$(PASSWORD)'
    rootDirectory: 'dist'
    filePatterns: '**'
    remoteDirectory: '/wwwroot/'
    clean: true
    cleanContents: false
    preservePaths: true
    trustSSL: true

